package com.lzx.generator.dao;

import com.lzx.generator.model.EcsBrand;
import com.lzx.generator.model.EcsBrandExample;
import com.lzx.generator.model.EcsBrandWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_brand
     *
     * @mbg.generated
     */
    long countByExample(EcsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_brand
     *
     * @mbg.generated
     */
    int deleteByExample(EcsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_brand
     *
     * @mbg.generated
     */
    int insert(EcsBrandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_brand
     *
     * @mbg.generated
     */
    int insertSelective(EcsBrandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_brand
     *
     * @mbg.generated
     */
    List<EcsBrandWithBLOBs> selectByExampleWithBLOBs(EcsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_brand
     *
     * @mbg.generated
     */
    List<EcsBrand> selectByExample(EcsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_brand
     *
     * @mbg.generated
     */
    EcsBrandWithBLOBs selectByPrimaryKey(Short brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsBrandWithBLOBs record, @Param("example") EcsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_brand
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsBrandWithBLOBs record, @Param("example") EcsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsBrand record, @Param("example") EcsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsBrandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsBrandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsBrand record);
}