package com.lzx.generator.dao;

import com.lzx.generator.model.EcsBackGoods;
import com.lzx.generator.model.EcsBackGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsBackGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_goods
     *
     * @mbg.generated
     */
    long countByExample(EcsBackGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_goods
     *
     * @mbg.generated
     */
    int deleteByExample(EcsBackGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_goods
     *
     * @mbg.generated
     */
    int insert(EcsBackGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_goods
     *
     * @mbg.generated
     */
    int insertSelective(EcsBackGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_goods
     *
     * @mbg.generated
     */
    List<EcsBackGoods> selectByExampleWithBLOBs(EcsBackGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_goods
     *
     * @mbg.generated
     */
    List<EcsBackGoods> selectByExample(EcsBackGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_goods
     *
     * @mbg.generated
     */
    EcsBackGoods selectByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsBackGoods record, @Param("example") EcsBackGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_goods
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsBackGoods record, @Param("example") EcsBackGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsBackGoods record, @Param("example") EcsBackGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsBackGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsBackGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_back_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsBackGoods record);
}