package com.lzx.generator.dao;

import com.lzx.generator.model.EcsCart;
import com.lzx.generator.model.EcsCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart
     *
     * @mbg.generated
     */
    long countByExample(EcsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart
     *
     * @mbg.generated
     */
    int deleteByExample(EcsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart
     *
     * @mbg.generated
     */
    int insert(EcsCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart
     *
     * @mbg.generated
     */
    int insertSelective(EcsCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart
     *
     * @mbg.generated
     */
    List<EcsCart> selectByExampleWithBLOBs(EcsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart
     *
     * @mbg.generated
     */
    List<EcsCart> selectByExample(EcsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart
     *
     * @mbg.generated
     */
    EcsCart selectByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsCart record, @Param("example") EcsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsCart record, @Param("example") EcsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsCart record, @Param("example") EcsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsCart record);
}