package com.lzx.generator.dao;

import com.lzx.generator.model.EcsCategory;
import com.lzx.generator.model.EcsCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbg.generated
     */
    long countByExample(EcsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbg.generated
     */
    int deleteByExample(EcsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbg.generated
     */
    int insert(EcsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbg.generated
     */
    int insertSelective(EcsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbg.generated
     */
    List<EcsCategory> selectByExample(EcsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbg.generated
     */
    EcsCategory selectByPrimaryKey(Short catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsCategory record, @Param("example") EcsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsCategory record, @Param("example") EcsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsCategory record);
}