package com.lzx.generator.dao;

import com.lzx.generator.model.EcsEgoComment;
import com.lzx.generator.model.EcsEgoCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsEgoCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_comment
     *
     * @mbg.generated
     */
    long countByExample(EcsEgoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_comment
     *
     * @mbg.generated
     */
    int deleteByExample(EcsEgoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_comment
     *
     * @mbg.generated
     */
    int insert(EcsEgoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_comment
     *
     * @mbg.generated
     */
    int insertSelective(EcsEgoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_comment
     *
     * @mbg.generated
     */
    List<EcsEgoComment> selectByExampleWithBLOBs(EcsEgoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_comment
     *
     * @mbg.generated
     */
    List<EcsEgoComment> selectByExample(EcsEgoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_comment
     *
     * @mbg.generated
     */
    EcsEgoComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsEgoComment record, @Param("example") EcsEgoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_comment
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsEgoComment record, @Param("example") EcsEgoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsEgoComment record, @Param("example") EcsEgoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsEgoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsEgoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsEgoComment record);
}