package com.lzx.generator.dao;

import com.lzx.generator.model.EcsEgoVideo;
import com.lzx.generator.model.EcsEgoVideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsEgoVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    long countByExample(EcsEgoVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    int deleteByExample(EcsEgoVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    int insert(EcsEgoVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    int insertSelective(EcsEgoVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    List<EcsEgoVideo> selectByExampleWithBLOBs(EcsEgoVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    List<EcsEgoVideo> selectByExample(EcsEgoVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    EcsEgoVideo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsEgoVideo record, @Param("example") EcsEgoVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsEgoVideo record, @Param("example") EcsEgoVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsEgoVideo record, @Param("example") EcsEgoVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsEgoVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsEgoVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_video
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsEgoVideo record);
}