package com.lzx.generator.dao;

import com.lzx.generator.model.EcsKeywords;
import com.lzx.generator.model.EcsKeywordsExample;
import com.lzx.generator.model.EcsKeywordsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsKeywordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_keywords
     *
     * @mbg.generated
     */
    long countByExample(EcsKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_keywords
     *
     * @mbg.generated
     */
    int deleteByExample(EcsKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_keywords
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(EcsKeywordsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_keywords
     *
     * @mbg.generated
     */
    int insert(EcsKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_keywords
     *
     * @mbg.generated
     */
    int insertSelective(EcsKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_keywords
     *
     * @mbg.generated
     */
    List<EcsKeywords> selectByExample(EcsKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_keywords
     *
     * @mbg.generated
     */
    EcsKeywords selectByPrimaryKey(EcsKeywordsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_keywords
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsKeywords record, @Param("example") EcsKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_keywords
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsKeywords record, @Param("example") EcsKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_keywords
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_keywords
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsKeywords record);
}