package com.lzx.generator.dao;

import com.lzx.generator.model.EcsOrderInfo;
import com.lzx.generator.model.EcsOrderInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsOrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbg.generated
     */
    long countByExample(EcsOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbg.generated
     */
    int deleteByExample(EcsOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbg.generated
     */
    int insert(EcsOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbg.generated
     */
    int insertSelective(EcsOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbg.generated
     */
    List<EcsOrderInfo> selectByExampleWithBLOBs(EcsOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbg.generated
     */
    List<EcsOrderInfo> selectByExample(EcsOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbg.generated
     */
    EcsOrderInfo selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsOrderInfo record, @Param("example") EcsOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsOrderInfo record, @Param("example") EcsOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsOrderInfo record, @Param("example") EcsOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsOrderInfo record);
}