package com.lzx.generator.dao;

import com.lzx.generator.model.EcsQuestion;
import com.lzx.generator.model.EcsQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    long countByExample(EcsQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    int deleteByExample(EcsQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    int insert(EcsQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    int insertSelective(EcsQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    List<EcsQuestion> selectByExampleWithBLOBs(EcsQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    List<EcsQuestion> selectByExample(EcsQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    EcsQuestion selectByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsQuestion record, @Param("example") EcsQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsQuestion record, @Param("example") EcsQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsQuestion record, @Param("example") EcsQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsQuestion record);
}