package com.lzx.generator.dao;

import com.lzx.generator.model.EcsRole;
import com.lzx.generator.model.EcsRoleExample;
import com.lzx.generator.model.EcsRoleWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    long countByExample(EcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    int deleteByExample(EcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    int insert(EcsRoleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    int insertSelective(EcsRoleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    List<EcsRoleWithBLOBs> selectByExampleWithBLOBs(EcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    List<EcsRole> selectByExample(EcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    EcsRoleWithBLOBs selectByPrimaryKey(Short roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsRoleWithBLOBs record, @Param("example") EcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsRoleWithBLOBs record, @Param("example") EcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsRole record, @Param("example") EcsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsRoleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsRoleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsRole record);
}