package com.lzx.generator.dao;

import com.lzx.generator.model.EcsRegFields;
import com.lzx.generator.model.EcsRegFieldsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsRegFieldsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_reg_fields
     *
     * @mbg.generated
     */
    long countByExample(EcsRegFieldsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_reg_fields
     *
     * @mbg.generated
     */
    int deleteByExample(EcsRegFieldsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_reg_fields
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_reg_fields
     *
     * @mbg.generated
     */
    int insert(EcsRegFields record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_reg_fields
     *
     * @mbg.generated
     */
    int insertSelective(EcsRegFields record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_reg_fields
     *
     * @mbg.generated
     */
    List<EcsRegFields> selectByExample(EcsRegFieldsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_reg_fields
     *
     * @mbg.generated
     */
    EcsRegFields selectByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_reg_fields
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsRegFields record, @Param("example") EcsRegFieldsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_reg_fields
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsRegFields record, @Param("example") EcsRegFieldsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_reg_fields
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsRegFields record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_reg_fields
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsRegFields record);
}