package com.lzx.generator.dao;

import com.lzx.generator.model.EcsSnatchLog;
import com.lzx.generator.model.EcsSnatchLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsSnatchLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_snatch_log
     *
     * @mbg.generated
     */
    long countByExample(EcsSnatchLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_snatch_log
     *
     * @mbg.generated
     */
    int deleteByExample(EcsSnatchLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_snatch_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_snatch_log
     *
     * @mbg.generated
     */
    int insert(EcsSnatchLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_snatch_log
     *
     * @mbg.generated
     */
    int insertSelective(EcsSnatchLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_snatch_log
     *
     * @mbg.generated
     */
    List<EcsSnatchLog> selectByExample(EcsSnatchLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_snatch_log
     *
     * @mbg.generated
     */
    EcsSnatchLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_snatch_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsSnatchLog record, @Param("example") EcsSnatchLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_snatch_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsSnatchLog record, @Param("example") EcsSnatchLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_snatch_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsSnatchLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_snatch_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsSnatchLog record);
}