package com.lzx.generator.dao;

import com.lzx.generator.model.EcsShipping;
import com.lzx.generator.model.EcsShippingExample;
import com.lzx.generator.model.EcsShippingWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shipping
     *
     * @mbg.generated
     */
    long countByExample(EcsShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shipping
     *
     * @mbg.generated
     */
    int deleteByExample(EcsShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shipping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Byte shippingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shipping
     *
     * @mbg.generated
     */
    int insert(EcsShippingWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shipping
     *
     * @mbg.generated
     */
    int insertSelective(EcsShippingWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shipping
     *
     * @mbg.generated
     */
    List<EcsShippingWithBLOBs> selectByExampleWithBLOBs(EcsShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shipping
     *
     * @mbg.generated
     */
    List<EcsShipping> selectByExample(EcsShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shipping
     *
     * @mbg.generated
     */
    EcsShippingWithBLOBs selectByPrimaryKey(Byte shippingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shipping
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsShippingWithBLOBs record, @Param("example") EcsShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shipping
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsShippingWithBLOBs record, @Param("example") EcsShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shipping
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsShipping record, @Param("example") EcsShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shipping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsShippingWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shipping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsShippingWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_shipping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsShipping record);
}