package com.lzx.generator.dao;

import com.lzx.generator.model.EcsSupplierAdminUser;
import com.lzx.generator.model.EcsSupplierAdminUserExample;
import com.lzx.generator.model.EcsSupplierAdminUserWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsSupplierAdminUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_user
     *
     * @mbg.generated
     */
    long countByExample(EcsSupplierAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_user
     *
     * @mbg.generated
     */
    int deleteByExample(EcsSupplierAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_user
     *
     * @mbg.generated
     */
    int insert(EcsSupplierAdminUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_user
     *
     * @mbg.generated
     */
    int insertSelective(EcsSupplierAdminUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_user
     *
     * @mbg.generated
     */
    List<EcsSupplierAdminUserWithBLOBs> selectByExampleWithBLOBs(EcsSupplierAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_user
     *
     * @mbg.generated
     */
    List<EcsSupplierAdminUser> selectByExample(EcsSupplierAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_user
     *
     * @mbg.generated
     */
    EcsSupplierAdminUserWithBLOBs selectByPrimaryKey(Short userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsSupplierAdminUserWithBLOBs record, @Param("example") EcsSupplierAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_user
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsSupplierAdminUserWithBLOBs record, @Param("example") EcsSupplierAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsSupplierAdminUser record, @Param("example") EcsSupplierAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsSupplierAdminUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsSupplierAdminUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_admin_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsSupplierAdminUser record);
}