package com.lzx.generator.dao;

import com.lzx.generator.model.EcsSupplierRank;
import com.lzx.generator.model.EcsSupplierRankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsSupplierRankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rank
     *
     * @mbg.generated
     */
    long countByExample(EcsSupplierRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rank
     *
     * @mbg.generated
     */
    int deleteByExample(EcsSupplierRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rank
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Byte rankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rank
     *
     * @mbg.generated
     */
    int insert(EcsSupplierRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rank
     *
     * @mbg.generated
     */
    int insertSelective(EcsSupplierRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rank
     *
     * @mbg.generated
     */
    List<EcsSupplierRank> selectByExample(EcsSupplierRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rank
     *
     * @mbg.generated
     */
    EcsSupplierRank selectByPrimaryKey(Byte rankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rank
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsSupplierRank record, @Param("example") EcsSupplierRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rank
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsSupplierRank record, @Param("example") EcsSupplierRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rank
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsSupplierRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rank
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsSupplierRank record);
}