package com.lzx.generator.dao;

import com.lzx.generator.model.EcsSupplierStreet;
import com.lzx.generator.model.EcsSupplierStreetExample;
import com.lzx.generator.model.EcsSupplierStreetWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsSupplierStreetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_street
     *
     * @mbg.generated
     */
    long countByExample(EcsSupplierStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_street
     *
     * @mbg.generated
     */
    int deleteByExample(EcsSupplierStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_street
     *
     * @mbg.generated
     */
    int insert(EcsSupplierStreetWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_street
     *
     * @mbg.generated
     */
    int insertSelective(EcsSupplierStreetWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_street
     *
     * @mbg.generated
     */
    List<EcsSupplierStreetWithBLOBs> selectByExampleWithBLOBs(EcsSupplierStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_street
     *
     * @mbg.generated
     */
    List<EcsSupplierStreet> selectByExample(EcsSupplierStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_street
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsSupplierStreetWithBLOBs record, @Param("example") EcsSupplierStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_street
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsSupplierStreetWithBLOBs record, @Param("example") EcsSupplierStreetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_street
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsSupplierStreet record, @Param("example") EcsSupplierStreetExample example);
}