package com.lzx.generator.dao;

import com.lzx.generator.model.EcsSuppliers;
import com.lzx.generator.model.EcsSuppliersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsSuppliersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_suppliers
     *
     * @mbg.generated
     */
    long countByExample(EcsSuppliersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_suppliers
     *
     * @mbg.generated
     */
    int deleteByExample(EcsSuppliersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_suppliers
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short suppliersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_suppliers
     *
     * @mbg.generated
     */
    int insert(EcsSuppliers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_suppliers
     *
     * @mbg.generated
     */
    int insertSelective(EcsSuppliers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_suppliers
     *
     * @mbg.generated
     */
    List<EcsSuppliers> selectByExampleWithBLOBs(EcsSuppliersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_suppliers
     *
     * @mbg.generated
     */
    List<EcsSuppliers> selectByExample(EcsSuppliersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_suppliers
     *
     * @mbg.generated
     */
    EcsSuppliers selectByPrimaryKey(Short suppliersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_suppliers
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsSuppliers record, @Param("example") EcsSuppliersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_suppliers
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsSuppliers record, @Param("example") EcsSuppliersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_suppliers
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsSuppliers record, @Param("example") EcsSuppliersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_suppliers
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsSuppliers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_suppliers
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsSuppliers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_suppliers
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsSuppliers record);
}