package com.lzx.generator.dao;

import com.lzx.generator.model.EcsSupplierRebateLog;
import com.lzx.generator.model.EcsSupplierRebateLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsSupplierRebateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate_log
     *
     * @mbg.generated
     */
    long countByExample(EcsSupplierRebateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate_log
     *
     * @mbg.generated
     */
    int deleteByExample(EcsSupplierRebateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate_log
     *
     * @mbg.generated
     */
    int insert(EcsSupplierRebateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate_log
     *
     * @mbg.generated
     */
    int insertSelective(EcsSupplierRebateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate_log
     *
     * @mbg.generated
     */
    List<EcsSupplierRebateLog> selectByExample(EcsSupplierRebateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate_log
     *
     * @mbg.generated
     */
    EcsSupplierRebateLog selectByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsSupplierRebateLog record, @Param("example") EcsSupplierRebateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsSupplierRebateLog record, @Param("example") EcsSupplierRebateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsSupplierRebateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsSupplierRebateLog record);
}