package com.lzx.generator.dao;

import com.lzx.generator.model.EcsTakegoodsTypeGoods;
import com.lzx.generator.model.EcsTakegoodsTypeGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsTakegoodsTypeGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type_goods
     *
     * @mbg.generated
     */
    long countByExample(EcsTakegoodsTypeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type_goods
     *
     * @mbg.generated
     */
    int deleteByExample(EcsTakegoodsTypeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer tgTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type_goods
     *
     * @mbg.generated
     */
    int insert(EcsTakegoodsTypeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type_goods
     *
     * @mbg.generated
     */
    int insertSelective(EcsTakegoodsTypeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type_goods
     *
     * @mbg.generated
     */
    List<EcsTakegoodsTypeGoods> selectByExample(EcsTakegoodsTypeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type_goods
     *
     * @mbg.generated
     */
    EcsTakegoodsTypeGoods selectByPrimaryKey(Integer tgTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsTakegoodsTypeGoods record, @Param("example") EcsTakegoodsTypeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsTakegoodsTypeGoods record, @Param("example") EcsTakegoodsTypeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsTakegoodsTypeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsTakegoodsTypeGoods record);
}