package com.lzx.generator.dao;

import com.lzx.generator.model.EcsVote;
import com.lzx.generator.model.EcsVoteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsVoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_vote
     *
     * @mbg.generated
     */
    long countByExample(EcsVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_vote
     *
     * @mbg.generated
     */
    int deleteByExample(EcsVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_vote
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short voteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_vote
     *
     * @mbg.generated
     */
    int insert(EcsVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_vote
     *
     * @mbg.generated
     */
    int insertSelective(EcsVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_vote
     *
     * @mbg.generated
     */
    List<EcsVote> selectByExample(EcsVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_vote
     *
     * @mbg.generated
     */
    EcsVote selectByPrimaryKey(Short voteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_vote
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsVote record, @Param("example") EcsVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_vote
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsVote record, @Param("example") EcsVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_vote
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_vote
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsVote record);
}