package com.lzx.generator.dao;

import com.lzx.generator.model.EcsWeixinAct;
import com.lzx.generator.model.EcsWeixinActExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsWeixinActMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    long countByExample(EcsWeixinActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    int deleteByExample(EcsWeixinActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    int insert(EcsWeixinAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    int insertSelective(EcsWeixinAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    List<EcsWeixinAct> selectByExampleWithBLOBs(EcsWeixinActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    List<EcsWeixinAct> selectByExample(EcsWeixinActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    EcsWeixinAct selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsWeixinAct record, @Param("example") EcsWeixinActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsWeixinAct record, @Param("example") EcsWeixinActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsWeixinAct record, @Param("example") EcsWeixinActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsWeixinAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsWeixinAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_act
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsWeixinAct record);
}