package generator.model;

public class EcsBrandWithBLOBs extends EcsBrand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_brand.brand_desc
     *
     * @mbg.generated
     */
    private String brandDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_brand.wap_brand_desc
     *
     * @mbg.generated
     */
    private String wapBrandDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_brand.brand_desc
     *
     * @return the value of ecs_brand.brand_desc
     *
     * @mbg.generated
     */
    public String getBrandDesc() {
        return brandDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_brand.brand_desc
     *
     * @param brandDesc the value for ecs_brand.brand_desc
     *
     * @mbg.generated
     */
    public void setBrandDesc(String brandDesc) {
        this.brandDesc = brandDesc == null ? null : brandDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_brand.wap_brand_desc
     *
     * @return the value of ecs_brand.wap_brand_desc
     *
     * @mbg.generated
     */
    public String getWapBrandDesc() {
        return wapBrandDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_brand.wap_brand_desc
     *
     * @param wapBrandDesc the value for ecs_brand.wap_brand_desc
     *
     * @mbg.generated
     */
    public void setWapBrandDesc(String wapBrandDesc) {
        this.wapBrandDesc = wapBrandDesc == null ? null : wapBrandDesc.trim();
    }
}