package generator.dao;

import generator.model.EcsAd;
import generator.model.EcsAdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    long countByExample(EcsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    int deleteByExample(EcsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    int insert(EcsAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    int insertSelective(EcsAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    List<EcsAd> selectByExampleWithBLOBs(EcsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    List<EcsAd> selectByExample(EcsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    EcsAd selectByPrimaryKey(Short adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsAd record, @Param("example") EcsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsAd record, @Param("example") EcsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsAd record, @Param("example") EcsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsAd record);
}