package generator.dao;

import generator.model.EcsAdminAction;
import generator.model.EcsAdminActionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsAdminActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_action
     *
     * @mbg.generated
     */
    long countByExample(EcsAdminActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_action
     *
     * @mbg.generated
     */
    int deleteByExample(EcsAdminActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_action
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_action
     *
     * @mbg.generated
     */
    int insert(EcsAdminAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_action
     *
     * @mbg.generated
     */
    int insertSelective(EcsAdminAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_action
     *
     * @mbg.generated
     */
    List<EcsAdminAction> selectByExample(EcsAdminActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_action
     *
     * @mbg.generated
     */
    EcsAdminAction selectByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_action
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsAdminAction record, @Param("example") EcsAdminActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_action
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsAdminAction record, @Param("example") EcsAdminActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_action
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsAdminAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_action
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsAdminAction record);
}