package generator.dao;

import generator.model.EcsAdminUser;
import generator.model.EcsAdminUserExample;
import generator.model.EcsAdminUserWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsAdminUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_user
     *
     * @mbg.generated
     */
    long countByExample(EcsAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_user
     *
     * @mbg.generated
     */
    int deleteByExample(EcsAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_user
     *
     * @mbg.generated
     */
    int insert(EcsAdminUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_user
     *
     * @mbg.generated
     */
    int insertSelective(EcsAdminUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_user
     *
     * @mbg.generated
     */
    List<EcsAdminUserWithBLOBs> selectByExampleWithBLOBs(EcsAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_user
     *
     * @mbg.generated
     */
    List<EcsAdminUser> selectByExample(EcsAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_user
     *
     * @mbg.generated
     */
    EcsAdminUserWithBLOBs selectByPrimaryKey(Short userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsAdminUserWithBLOBs record, @Param("example") EcsAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_user
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsAdminUserWithBLOBs record, @Param("example") EcsAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsAdminUser record, @Param("example") EcsAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsAdminUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsAdminUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_admin_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsAdminUser record);
}