package generator.dao;

import generator.model.EcsChatThirdCustomer;
import generator.model.EcsChatThirdCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsChatThirdCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_chat_third_customer
     *
     * @mbg.generated
     */
    long countByExample(EcsChatThirdCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_chat_third_customer
     *
     * @mbg.generated
     */
    int deleteByExample(EcsChatThirdCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_chat_third_customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_chat_third_customer
     *
     * @mbg.generated
     */
    int insert(EcsChatThirdCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_chat_third_customer
     *
     * @mbg.generated
     */
    int insertSelective(EcsChatThirdCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_chat_third_customer
     *
     * @mbg.generated
     */
    List<EcsChatThirdCustomer> selectByExample(EcsChatThirdCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_chat_third_customer
     *
     * @mbg.generated
     */
    EcsChatThirdCustomer selectByPrimaryKey(Integer cusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_chat_third_customer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsChatThirdCustomer record, @Param("example") EcsChatThirdCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_chat_third_customer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsChatThirdCustomer record, @Param("example") EcsChatThirdCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_chat_third_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsChatThirdCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_chat_third_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsChatThirdCustomer record);
}