package generator.dao;

import generator.model.EcsCatRecommendExample;
import generator.model.EcsCatRecommendKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsCatRecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cat_recommend
     *
     * @mbg.generated
     */
    long countByExample(EcsCatRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cat_recommend
     *
     * @mbg.generated
     */
    int deleteByExample(EcsCatRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cat_recommend
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(EcsCatRecommendKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cat_recommend
     *
     * @mbg.generated
     */
    int insert(EcsCatRecommendKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cat_recommend
     *
     * @mbg.generated
     */
    int insertSelective(EcsCatRecommendKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cat_recommend
     *
     * @mbg.generated
     */
    List<EcsCatRecommendKey> selectByExample(EcsCatRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cat_recommend
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsCatRecommendKey record, @Param("example") EcsCatRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cat_recommend
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsCatRecommendKey record, @Param("example") EcsCatRecommendExample example);
}