package generator.dao;

import generator.model.EcsCartCombo;
import generator.model.EcsCartComboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsCartComboMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart_combo
     *
     * @mbg.generated
     */
    long countByExample(EcsCartComboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart_combo
     *
     * @mbg.generated
     */
    int deleteByExample(EcsCartComboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart_combo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart_combo
     *
     * @mbg.generated
     */
    int insert(EcsCartCombo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart_combo
     *
     * @mbg.generated
     */
    int insertSelective(EcsCartCombo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart_combo
     *
     * @mbg.generated
     */
    List<EcsCartCombo> selectByExampleWithBLOBs(EcsCartComboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart_combo
     *
     * @mbg.generated
     */
    List<EcsCartCombo> selectByExample(EcsCartComboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart_combo
     *
     * @mbg.generated
     */
    EcsCartCombo selectByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart_combo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsCartCombo record, @Param("example") EcsCartComboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart_combo
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsCartCombo record, @Param("example") EcsCartComboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart_combo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsCartCombo record, @Param("example") EcsCartComboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart_combo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsCartCombo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart_combo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsCartCombo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_cart_combo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsCartCombo record);
}