package generator.dao;

import generator.model.EcsDistribSort;
import generator.model.EcsDistribSortExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsDistribSortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distrib_sort
     *
     * @mbg.generated
     */
    long countByExample(EcsDistribSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distrib_sort
     *
     * @mbg.generated
     */
    int deleteByExample(EcsDistribSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distrib_sort
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distrib_sort
     *
     * @mbg.generated
     */
    int insert(EcsDistribSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distrib_sort
     *
     * @mbg.generated
     */
    int insertSelective(EcsDistribSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distrib_sort
     *
     * @mbg.generated
     */
    List<EcsDistribSort> selectByExample(EcsDistribSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distrib_sort
     *
     * @mbg.generated
     */
    EcsDistribSort selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distrib_sort
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsDistribSort record, @Param("example") EcsDistribSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distrib_sort
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsDistribSort record, @Param("example") EcsDistribSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distrib_sort
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsDistribSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distrib_sort
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsDistribSort record);
}