package generator.dao;

import generator.model.EcsEgoUserRelationship;
import generator.model.EcsEgoUserRelationshipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsEgoUserRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_user_relationship
     *
     * @mbg.generated
     */
    long countByExample(EcsEgoUserRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_user_relationship
     *
     * @mbg.generated
     */
    int deleteByExample(EcsEgoUserRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_user_relationship
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_user_relationship
     *
     * @mbg.generated
     */
    int insert(EcsEgoUserRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_user_relationship
     *
     * @mbg.generated
     */
    int insertSelective(EcsEgoUserRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_user_relationship
     *
     * @mbg.generated
     */
    List<EcsEgoUserRelationship> selectByExample(EcsEgoUserRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_user_relationship
     *
     * @mbg.generated
     */
    EcsEgoUserRelationship selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_user_relationship
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsEgoUserRelationship record, @Param("example") EcsEgoUserRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_user_relationship
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsEgoUserRelationship record, @Param("example") EcsEgoUserRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_user_relationship
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsEgoUserRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_user_relationship
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsEgoUserRelationship record);
}