package generator.dao;

import generator.model.EcsErrorLog;
import generator.model.EcsErrorLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsErrorLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_error_log
     *
     * @mbg.generated
     */
    long countByExample(EcsErrorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_error_log
     *
     * @mbg.generated
     */
    int deleteByExample(EcsErrorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_error_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_error_log
     *
     * @mbg.generated
     */
    int insert(EcsErrorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_error_log
     *
     * @mbg.generated
     */
    int insertSelective(EcsErrorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_error_log
     *
     * @mbg.generated
     */
    List<EcsErrorLog> selectByExample(EcsErrorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_error_log
     *
     * @mbg.generated
     */
    EcsErrorLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_error_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsErrorLog record, @Param("example") EcsErrorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_error_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsErrorLog record, @Param("example") EcsErrorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_error_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsErrorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_error_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsErrorLog record);
}