package generator.dao;

import generator.model.EcsEgoQaAnswer;
import generator.model.EcsEgoQaAnswerExample;
import generator.model.EcsEgoQaAnswerWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsEgoQaAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    long countByExample(EcsEgoQaAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    int deleteByExample(EcsEgoQaAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    int insert(EcsEgoQaAnswerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    int insertSelective(EcsEgoQaAnswerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    List<EcsEgoQaAnswerWithBLOBs> selectByExampleWithBLOBs(EcsEgoQaAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    List<EcsEgoQaAnswer> selectByExample(EcsEgoQaAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    EcsEgoQaAnswerWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsEgoQaAnswerWithBLOBs record, @Param("example") EcsEgoQaAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsEgoQaAnswerWithBLOBs record, @Param("example") EcsEgoQaAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsEgoQaAnswer record, @Param("example") EcsEgoQaAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsEgoQaAnswerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsEgoQaAnswerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_ego_qa_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsEgoQaAnswer record);
}