package generator.dao;

import generator.model.EcsGoodsActivity;
import generator.model.EcsGoodsActivityExample;
import generator.model.EcsGoodsActivityWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsGoodsActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    long countByExample(EcsGoodsActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    int deleteByExample(EcsGoodsActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    int insert(EcsGoodsActivityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    int insertSelective(EcsGoodsActivityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    List<EcsGoodsActivityWithBLOBs> selectByExampleWithBLOBs(EcsGoodsActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    List<EcsGoodsActivity> selectByExample(EcsGoodsActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    EcsGoodsActivityWithBLOBs selectByPrimaryKey(Integer actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsGoodsActivityWithBLOBs record, @Param("example") EcsGoodsActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsGoodsActivityWithBLOBs record, @Param("example") EcsGoodsActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsGoodsActivity record, @Param("example") EcsGoodsActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsGoodsActivityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsGoodsActivityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsGoodsActivity record);
}