package generator.dao;

import generator.model.EcsSupplierCatRecommend;
import generator.model.EcsSupplierCatRecommendExample;
import generator.model.EcsSupplierCatRecommendKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsSupplierCatRecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_cat_recommend
     *
     * @mbg.generated
     */
    long countByExample(EcsSupplierCatRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_cat_recommend
     *
     * @mbg.generated
     */
    int deleteByExample(EcsSupplierCatRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_cat_recommend
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(EcsSupplierCatRecommendKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_cat_recommend
     *
     * @mbg.generated
     */
    int insert(EcsSupplierCatRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_cat_recommend
     *
     * @mbg.generated
     */
    int insertSelective(EcsSupplierCatRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_cat_recommend
     *
     * @mbg.generated
     */
    List<EcsSupplierCatRecommend> selectByExample(EcsSupplierCatRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_cat_recommend
     *
     * @mbg.generated
     */
    EcsSupplierCatRecommend selectByPrimaryKey(EcsSupplierCatRecommendKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_cat_recommend
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsSupplierCatRecommend record, @Param("example") EcsSupplierCatRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_cat_recommend
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsSupplierCatRecommend record, @Param("example") EcsSupplierCatRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_cat_recommend
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsSupplierCatRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_cat_recommend
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsSupplierCatRecommend record);
}