package generator.dao;

import generator.model.EcsSupplierRebate;
import generator.model.EcsSupplierRebateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsSupplierRebateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate
     *
     * @mbg.generated
     */
    long countByExample(EcsSupplierRebateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate
     *
     * @mbg.generated
     */
    int deleteByExample(EcsSupplierRebateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer rebateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate
     *
     * @mbg.generated
     */
    int insert(EcsSupplierRebate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate
     *
     * @mbg.generated
     */
    int insertSelective(EcsSupplierRebate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate
     *
     * @mbg.generated
     */
    List<EcsSupplierRebate> selectByExample(EcsSupplierRebateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate
     *
     * @mbg.generated
     */
    EcsSupplierRebate selectByPrimaryKey(Integer rebateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsSupplierRebate record, @Param("example") EcsSupplierRebateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsSupplierRebate record, @Param("example") EcsSupplierRebateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsSupplierRebate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_rebate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsSupplierRebate record);
}