package generator.dao;

import generator.model.EcsSupplierShopConfig;
import generator.model.EcsSupplierShopConfigExample;
import generator.model.EcsSupplierShopConfigKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsSupplierShopConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_shop_config
     *
     * @mbg.generated
     */
    long countByExample(EcsSupplierShopConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_shop_config
     *
     * @mbg.generated
     */
    int deleteByExample(EcsSupplierShopConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_shop_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(EcsSupplierShopConfigKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_shop_config
     *
     * @mbg.generated
     */
    int insert(EcsSupplierShopConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_shop_config
     *
     * @mbg.generated
     */
    int insertSelective(EcsSupplierShopConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_shop_config
     *
     * @mbg.generated
     */
    List<EcsSupplierShopConfig> selectByExampleWithBLOBs(EcsSupplierShopConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_shop_config
     *
     * @mbg.generated
     */
    List<EcsSupplierShopConfig> selectByExample(EcsSupplierShopConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_shop_config
     *
     * @mbg.generated
     */
    EcsSupplierShopConfig selectByPrimaryKey(EcsSupplierShopConfigKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_shop_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsSupplierShopConfig record, @Param("example") EcsSupplierShopConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_shop_config
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsSupplierShopConfig record, @Param("example") EcsSupplierShopConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_shop_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsSupplierShopConfig record, @Param("example") EcsSupplierShopConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_shop_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsSupplierShopConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_shop_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsSupplierShopConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_shop_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsSupplierShopConfig record);
}