package generator.dao;

import generator.model.EcsVolumePrice;
import generator.model.EcsVolumePriceExample;
import generator.model.EcsVolumePriceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsVolumePriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_volume_price
     *
     * @mbg.generated
     */
    long countByExample(EcsVolumePriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_volume_price
     *
     * @mbg.generated
     */
    int deleteByExample(EcsVolumePriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_volume_price
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(EcsVolumePriceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_volume_price
     *
     * @mbg.generated
     */
    int insert(EcsVolumePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_volume_price
     *
     * @mbg.generated
     */
    int insertSelective(EcsVolumePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_volume_price
     *
     * @mbg.generated
     */
    List<EcsVolumePrice> selectByExample(EcsVolumePriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_volume_price
     *
     * @mbg.generated
     */
    EcsVolumePrice selectByPrimaryKey(EcsVolumePriceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_volume_price
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsVolumePrice record, @Param("example") EcsVolumePriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_volume_price
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsVolumePrice record, @Param("example") EcsVolumePriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_volume_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsVolumePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_volume_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsVolumePrice record);
}