package generator.dao;

import generator.model.EcsValidateRecord;
import generator.model.EcsValidateRecordExample;
import generator.model.EcsValidateRecordWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsValidateRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_validate_record
     *
     * @mbg.generated
     */
    long countByExample(EcsValidateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_validate_record
     *
     * @mbg.generated
     */
    int deleteByExample(EcsValidateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_validate_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String recordKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_validate_record
     *
     * @mbg.generated
     */
    int insert(EcsValidateRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_validate_record
     *
     * @mbg.generated
     */
    int insertSelective(EcsValidateRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_validate_record
     *
     * @mbg.generated
     */
    List<EcsValidateRecordWithBLOBs> selectByExampleWithBLOBs(EcsValidateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_validate_record
     *
     * @mbg.generated
     */
    List<EcsValidateRecord> selectByExample(EcsValidateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_validate_record
     *
     * @mbg.generated
     */
    EcsValidateRecordWithBLOBs selectByPrimaryKey(String recordKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_validate_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsValidateRecordWithBLOBs record, @Param("example") EcsValidateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_validate_record
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsValidateRecordWithBLOBs record, @Param("example") EcsValidateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_validate_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsValidateRecord record, @Param("example") EcsValidateRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_validate_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsValidateRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_validate_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsValidateRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_validate_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsValidateRecord record);
}