package generator.dao;

import generator.model.EcsWholesale;
import generator.model.EcsWholesaleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsWholesaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_wholesale
     *
     * @mbg.generated
     */
    long countByExample(EcsWholesaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_wholesale
     *
     * @mbg.generated
     */
    int deleteByExample(EcsWholesaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_wholesale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_wholesale
     *
     * @mbg.generated
     */
    int insert(EcsWholesale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_wholesale
     *
     * @mbg.generated
     */
    int insertSelective(EcsWholesale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_wholesale
     *
     * @mbg.generated
     */
    List<EcsWholesale> selectByExampleWithBLOBs(EcsWholesaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_wholesale
     *
     * @mbg.generated
     */
    List<EcsWholesale> selectByExample(EcsWholesaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_wholesale
     *
     * @mbg.generated
     */
    EcsWholesale selectByPrimaryKey(Integer actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_wholesale
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsWholesale record, @Param("example") EcsWholesaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_wholesale
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EcsWholesale record, @Param("example") EcsWholesaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_wholesale
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsWholesale record, @Param("example") EcsWholesaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_wholesale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsWholesale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_wholesale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EcsWholesale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_wholesale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsWholesale record);
}