package generator.dao;

import generator.model.EcsWeixinActlist;
import generator.model.EcsWeixinActlistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsWeixinActlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_actlist
     *
     * @mbg.generated
     */
    long countByExample(EcsWeixinActlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_actlist
     *
     * @mbg.generated
     */
    int deleteByExample(EcsWeixinActlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_actlist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_actlist
     *
     * @mbg.generated
     */
    int insert(EcsWeixinActlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_actlist
     *
     * @mbg.generated
     */
    int insertSelective(EcsWeixinActlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_actlist
     *
     * @mbg.generated
     */
    List<EcsWeixinActlist> selectByExample(EcsWeixinActlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_actlist
     *
     * @mbg.generated
     */
    EcsWeixinActlist selectByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_actlist
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EcsWeixinActlist record, @Param("example") EcsWeixinActlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_actlist
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EcsWeixinActlist record, @Param("example") EcsWeixinActlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_actlist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcsWeixinActlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_weixin_actlist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsWeixinActlist record);
}